package encryption_test

import (
	"encoding/base64"
	"strings"
	"testing"
	"time"

	"github.com/arandu-io/hesape/encryption"
)

// TestAGeneratedKeyParses is the base case, and it is the one that catches the
// two halves drifting: the generator writes an encoding and the parser reads
// one, and nothing else in the tree checks that they are the same encoding.
func TestAGeneratedKeyParses(t *testing.T) {
	key, err := encryption.ParseKey(encryption.GenerateKey())
	if err != nil {
		t.Fatalf("a key this application just generated was refused: %v", err)
	}
	if len(key) != encryption.KeySize {
		t.Errorf("the key parsed to %d bytes, want %d", len(key), encryption.KeySize)
	}
}

// TestTwoGeneratedKeysDiffer: a generator that is not random is a key that is
// not a secret, and the failure is invisible until someone else has the key.
func TestTwoGeneratedKeysDiffer(t *testing.T) {
	if encryption.GenerateKey() == encryption.GenerateKey() {
		t.Fatal("two generated keys are identical: the key is not random")
	}
}

// TestARawKeyIsAccepted. Not every key was generated by the command -- one
// written by hand into a .env has no prefix, and refusing it would make the
// file format stricter than it is documented to be.
func TestARawKeyIsAccepted(t *testing.T) {
	raw := strings.Repeat("k", encryption.KeySize)

	key, err := encryption.ParseKey(raw)
	if err != nil {
		t.Fatalf("a raw key of the right length was refused: %v", err)
	}
	if string(key) != raw {
		t.Errorf("the key came back as %q", key)
	}
}

// TestAKeyOfTheWrongLengthIsRefused, in both forms it can be written.
//
// This is the check that has to happen at boot. A short key does not fail a
// request; it signs everything with less entropy than the signature claims,
// and nothing observable goes wrong until it matters.
func TestAKeyOfTheWrongLengthIsRefused(t *testing.T) {
	short := strings.Repeat("k", encryption.KeySize-1)
	long := strings.Repeat("k", encryption.KeySize+1)

	for _, v := range []string{
		"",
		short,
		long,
		"base64:" + base64.StdEncoding.EncodeToString([]byte(short)),
		"base64:" + base64.StdEncoding.EncodeToString([]byte(long)),
	} {
		if _, err := encryption.ParseKey(v); err == nil {
			t.Errorf("a key of %d bytes was accepted", len(v))
		}
	}
}

// TestAnUnparseableKeySaysSoRatherThanSigningWithGarbage: "base64:" is a
// promise about what follows, and a value that breaks it is a typo in a .env,
// which is the moment a person can still fix it.
func TestAnUnparseableKeySaysSoRatherThanSigningWithGarbage(t *testing.T) {
	if _, err := encryption.ParseKey("base64:not base64 at all"); err == nil {
		t.Fatal("a key that is not base64 was accepted behind the base64 prefix")
	}
}

// TestTheErrorNamesTheCommandThatFixesIt. A message that reports a
// configuration error without the fix costs a search; there is exactly one way
// to produce a key, and this is where a person is told it.
func TestTheErrorNamesTheCommandThatFixesIt(t *testing.T) {
	_, err := encryption.ParseKey("")
	if err == nil {
		t.Fatal("an empty key was accepted")
	}
	if !strings.Contains(err.Error(), "aru key:generate") {
		t.Errorf("the error does not say how to fix it: %v", err)
	}
}

// TestAGeneratedKeySigns closes the loop the package exists for: the key that
// comes out of the command is a key the Signer can be built from.
func TestAGeneratedKeySigns(t *testing.T) {
	key, err := encryption.ParseKey(encryption.GenerateKey())
	if err != nil {
		t.Fatalf("parsing a generated key: %v", err)
	}

	s := encryption.NewSigner(key)
	got, err := s.Verify("verify-email", s.Sign("verify-email", "user-1", time.Hour))
	if err != nil {
		t.Fatalf("a token signed with a generated key was refused: %v", err)
	}
	if got != "user-1" {
		t.Errorf("the payload came back as %q", got)
	}
}
