package model

import (
	"context"
	"regexp"
	"testing"

	"github.com/arandu-io/hesape/database/query/grammars"
)

// orderedUUID is the text of a version 7 UUID: the five groups every uuid
// column accepts, with 7 as the version and 10 as the variant.
var orderedUUID = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

// uniqueNotes is the notes model with the key generated by the model rather
// than written by the caller.
func uniqueNotes() (*Model[note], *testConnection) {
	conn := newTestConnection()
	m := NewModel[note]("notes", conn, grammars.NewSQLiteGrammar(), &testProcessor{conn: conn}).UseUniqueIDs()
	m.Timestamps = false
	return m, conn
}

// TestUseUniqueIDsIsTheWholeKeyConfiguration: the two assignments every model
// with a generated key repeated are what the opt-in sets, and every instance
// the model makes carries it.
func TestUseUniqueIDsIsTheWholeKeyConfiguration(t *testing.T) {
	m, _ := uniqueNotes()
	if m.KeyType != "string" || m.Incrementing {
		t.Fatalf("KeyType = %q, Incrementing = %v, want string and false", m.KeyType, m.Incrementing)
	}
	instance, err := m.NewInstance(nil, false)
	if err != nil {
		t.Fatal(err)
	}
	if !instance.UsesUniqueIDs() {
		t.Fatal("an instance lost UseUniqueIDs, and its insert would write an empty key")
	}
}

// TestCreateGivesAnEmptyKeyAnOrderedID: no caller writes data.NewID by hand
// any more, so the insert itself has to carry an id.
func TestCreateGivesAnEmptyKeyAnOrderedID(t *testing.T) {
	m, conn := uniqueNotes()

	created, err := m.Create(context.Background(), acmeNotes, map[string]any{"body": "hello"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if !orderedUUID.MatchString(created.ID) {
		t.Fatalf("ID = %q, want a version 7 UUID", created.ID)
	}
	if !bound(conn.last().Bindings, created.ID) {
		t.Fatalf("the insert did not write the id the entity carries:\n%s\n%#v", conn.last().SQL, conn.last().Bindings)
	}
}

// TestSaveKeepsAKeyTheCallerSet: a caller that has to choose the id -- an
// import keeping the ids of another system -- still can.
func TestSaveKeepsAKeyTheCallerSet(t *testing.T) {
	m, conn := uniqueNotes()
	instance, err := m.NewInstance(nil, false)
	if err != nil {
		t.Fatal(err)
	}
	instance.Entity.ID = "chosen-id"
	instance.Entity.Body = "hello"

	if _, err := instance.Save(context.Background(), acmeNotes); err != nil {
		t.Fatalf("Save: %v", err)
	}
	if instance.Entity.ID != "chosen-id" || !bound(conn.last().Bindings, "chosen-id") {
		t.Fatalf("ID = %q, bindings %#v, want the id the caller set", instance.Entity.ID, conn.last().Bindings)
	}
}

// TestTheCreatingListenerSeesTheGeneratedKey: the key is filled before the
// event, so a listener that records or derives from the id has one.
func TestTheCreatingListenerSeesTheGeneratedKey(t *testing.T) {
	m, _ := uniqueNotes()
	var seen string
	m.RegisterModelEvent(Creating, func(created *Model[note]) error {
		seen = created.Entity.ID
		return nil
	})

	if _, err := m.Create(context.Background(), acmeNotes, map[string]any{"body": "hello"}); err != nil {
		t.Fatalf("Create: %v", err)
	}
	if !orderedUUID.MatchString(seen) {
		t.Fatalf("Creating saw ID %q, want the generated id", seen)
	}
}

// TestFillForInsertGivesEveryRowItsOwnKey: the bulk path writes the columns a
// save would have, and a save would have written a key.
func TestFillForInsertGivesEveryRowItsOwnKey(t *testing.T) {
	m, _ := uniqueNotes()

	rows, err := m.NewQuery().FillForInsert([]map[string]any{{"body": "a"}, {"body": "b", "id": "kept"}})
	if err != nil {
		t.Fatalf("FillForInsert: %v", err)
	}
	first, _ := rows[0]["id"].(string)
	if !orderedUUID.MatchString(first) {
		t.Errorf("first row id = %q, want a version 7 UUID", first)
	}
	if rows[1]["id"] != "kept" {
		t.Errorf("second row id = %v, want the id it was given", rows[1]["id"])
	}
}

// TestAnIncrementingModelIsLeftToTheDatabase: without the opt-in nothing is
// generated, and the key stays the database's to assign.
func TestAnIncrementingModelIsLeftToTheDatabase(t *testing.T) {
	m, conn := newUserModel()
	if _, err := m.Create(context.Background(), grant(), map[string]any{"name": "Ada"}); err != nil {
		t.Fatalf("Create: %v", err)
	}
	for _, binding := range conn.last().Bindings {
		if s, ok := binding.(string); ok && orderedUUID.MatchString(s) {
			t.Fatalf("an incrementing model was given a generated key: %#v", conn.last().Bindings)
		}
	}
}

// bound reports whether value is among the bindings of a statement.
func bound(bindings []any, value any) bool {
	for _, b := range bindings {
		if b == value {
			return true
		}
	}
	return false
}
